import {cp,rm,readFile,writeFile,mkdir} from 'node:fs/promises';
import {resolve,relative} from 'node:path';
import {EXCLUDED_ROUTES} from './legacy-policy.mjs';
import {POLICY_ROUTES} from './release-policy.mjs';
const root=resolve('.'),out=resolve('out');
if(relative(root,out)!=='out')throw new Error('Invalid export directory');
await rm(out,{recursive:true,force:true});
await cp(resolve('public'),out,{recursive:true});
const inventory=JSON.parse(await readFile('migration/inventory.json'));
const routes=[...inventory.routes.filter(route=>!EXCLUDED_ROUTES.has(route.path)),...POLICY_ROUTES];
const routePaths=routes.map(route=>route.path);
if(routePaths.length!==11||new Set(routePaths).size!==11)throw new Error('Sitemap must contain exactly 11 unique published routes');
if(routePaths.some(path=>!path.startsWith('/')||path.includes('?')||path.includes('#')))throw new Error('Sitemap route contains an invalid path');
const sitemap='<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+routes.map(r=>`<url><loc>https://slopestohope.org${r.path}</loc></url>`).join('')+'</urlset>\n';
if((sitemap.match(/<loc>/g)||[]).length!==11||/slopestohope\.com/i.test(sitemap))throw new Error('Generated sitemap failed host or route-count validation');
await writeFile(resolve(out,'sitemap.xml'),sitemap);
const robots='User-agent: *\nAllow: /\nDisallow: /cdn-cgi/\nSitemap: https://slopestohope.org/sitemap.xml\n';
if(!robots.includes('Sitemap: https://slopestohope.org/sitemap.xml')||/slopestohope\.com/i.test(robots))throw new Error('Generated robots.txt failed sitemap validation');
await writeFile(resolve(out,'robots.txt'),robots);
console.log(`Static export: ${routes.length} published routes, plus /staff/ compatibility redirect, in out/`);
